repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: ['--unsafe'] # required for !secret
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: v1.3.5
  #   hooks:
      # - id: clang-format
      # - id: clang-tidy
      # - id: cppcheck
      # - id: cpplint
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.6
    hooks:
    - id: clang-format
      types_or: [c++, c, cuda]
