name: Linting tools via pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - uses: pre-commit/action@v3.0.1

      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
